// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiXRsnbTEcVkvEVohzWKX4RWLA5axgfcg',
    appId: '1:371362030185:web:4eb8c780a328e9bdebb8f8',
    messagingSenderId: '371362030185',
    projectId: 'volunupt-5982a',
    authDomain: 'volunupt-5982a.firebaseapp.com',
    storageBucket: 'volunupt-5982a.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
    iosClientId: '371362030185-bhrs7r2q6npivvm7v5ma420a7n6epmke.apps.googleusercontent.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiXRsnbTEcVkvEVohzWKX4RWLA5axgfcg',
    appId: '1:371362030185:android:fc6951710a54bf8bebb8f8',
    messagingSenderId: '371362030185',
    projectId: 'volunupt-5982a',
    storageBucket: 'volunupt-5982a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiXRsnbTEcVkvEVohzWKX4RWLA5axgfcg',
    appId: '1:371362030185:ios:4eb8c780a328e9bdebb8f8',
    messagingSenderId: '371362030185',
    projectId: 'volunupt-5982a',
    storageBucket: 'volunupt-5982a.firebasestorage.app',
    iosBundleId: 'com.gregbhm.volunupt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiXRsnbTEcVkvEVohzWKX4RWLA5axgfcg',
    appId: '1:371362030185:macos:4eb8c780a328e9bdebb8f8',
    messagingSenderId: '371362030185',
    projectId: 'volunupt-5982a',
    storageBucket: 'volunupt-5982a.firebasestorage.app',
    iosBundleId: 'com.gregbhm.volunupt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiXRsnbTEcVkvEVohzWKX4RWLA5axgfcg',
    appId: '1:371362030185:windows:4eb8c780a328e9bdebb8f8',
    messagingSenderId: '371362030185',
    projectId: 'volunupt-5982a',
    authDomain: 'volunupt-5982a.firebaseapp.com',
    storageBucket: 'volunupt-5982a.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );
}